// 按需全局安装naiveui组件
import {
    create,
    NButton,
    NCard,
    NInput,
    NLayout,
    NLayoutSider,
    NLayoutHeader,
    NLayoutContent,
    NLayoutFooter,
    NIcon,
    NAvatar,
    NForm,
    NFormItem,
    NFormItemRow,
    NInputNumber,
    NColorPicker,
    NSelect,
    NTabs,
    NTabPane,
    NScrollbar,
    NModal,
    NConfigProvider,
    NCode,
    NMessageProvider,
    NMenu,
    NRadioGroup,
    NRadio,
    NSpace,
    NPopconfirm,
    NDropdown,
    NTag,
    NDivider,
    NDataTable,
    NDatePicker,
    NStatistic,
    NNumberAnimation
} from 'naive-ui'

const naive = create({
    components: [
        NButton,
        NCard,
        NInput,
        NLayout,
        NLayoutSider,
        NLayoutHeader,
        NLayoutContent,
        NLayoutFooter,
        NIcon,
        NAvatar,
        NForm,
        NFormItem,
        NFormItemRow,
        NInputNumber,
        NColorPicker,
        NSelect,
        NTabs,
        NTabPane,
        NScrollbar,
        NModal,
        NConfigProvider,
        NCode,
        NMessageProvider,
        NMenu,
        NRadioGroup,
        NRadio,
        NSpace,
        NPopconfirm,
        NDropdown,
        NTag,
        NDivider,
        NDataTable,
        NDatePicker,
        NStatistic,
        NNumberAnimation
    ]
})

export default naive